Sprint 6/step 1
VRbud/react-burger-yp pull request #10
Opened 2023-06-21 18:35 UTC by VRbud

2023-06-21 19:23 UTC, andryxxa93 requested changes
Супер!  `Cypress` тесты настроены и работают верно. 
Что понравилось:
- Все редьюсеры покрыты тестами. 
- Для одной функции `it` используется один `expect` - это хорошая практика.
- Успешный деплой проекта.
- Использовали `baseUrl`

Что необходимо исправить:
- Некоторые тесты падают
 <img width="422" alt="Снимок экрана 2023-06-21 в 22 18 42" src="https://github.com/VRbud/react-burger-yp/assets/60173362/3cf2ea89-ed5a-431f-ac1c-20c0f7d932b2">
- Необходимо удалить тесты cypress которые не относятся к проекту.

**Можно лучше**
- 643d69a5c3f7b9001cfa093c и другие строки селекторы повторяются несколько раз. 
Если строка-селектор повторяется более 2х раз в коде, значит, этот селектор нужно выносить в константу, чтобы можно было одним движением изменить его и не искать по всему коду дублирования этого селектора.

Удачных правок!

2023-06-21 21:14 UTC, VRbud commented
у меня все работает. 
Вы можете проверить с node 20 версии?

2023-06-21 22:33 UTC, VRbud commented
<img width="413" alt="Screenshot 2023-06-21 at 18 32 48" src="https://github.com/VRbud/react-burger-yp/assets/53311571/45ca12c5-6e9c-47f1-a264-c340bdcb4e6e">

2023-06-22 16:39 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-22 17:06 UTC, merged