Sprint 2/step 2
VRbud/react-burger-yp pull request #4
Opened 2023-04-21 14:36 UTC by VRbud

Добавляет всю функциональность из чек листа

2023-04-21 16:08 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/E1Q-f6L4Boqd-w> - активной должна быть только первая ссылка, а не все;

- По умолчанию булок быть не должно - <https://disk.yandex.com/i/qn060xPTA1nMqA>;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/T3kOMTSQpkGMJA>;

- В компоненте App-header иконка тоже должна быть обёрнута в ссылку;

- У вас возникает ошибка, если попытаться поменять ингредиенты местами: <https://disk.yandex.com/i/A1gWE7KOLbfVRw>;

- Нужно запретить нажатие кнопки, если пользователь выбрал только ингредиенты <https://disk.yandex.com/i/LUucN1Hh621dHQ>;

- со временем приложение будет разрастаться, появится новый функционал, если все будет в одном редьюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

  - загрузка данных ингредиентов
  - отправка заказа
  - работа конструктора
  - открытие модального окна ингредиента

  Для объединения редьюсеров используйте combineReducers
  <https://redux.js.org/api/combinereducers>

- Если значения нет, то нужно использовать null, а не пустой объект.

### **Сделает код лучше:**

- Следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

  В текущем приложении можно разделить на следующие файлы:

  - загрузка данных ингредиентов
  - работа конструктора
  - открытие ингредиента в попапе
  - оформление заказа

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-21 16:08 UTC, ArslanMustafin commented on src/services/reducers/ingredients.js
> +  bun: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-21 16:08 UTC, ArslanMustafin commented on src/services/reducers/ingredients.js
> +  currentIngredient: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-21 16:08 UTC, ArslanMustafin commented on src/services/reducers/ingredients.js
> +  orderData: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-21 16:08 UTC, ArslanMustafin commented on src/Types/types.js
> +
**Надо исправить:**

не забывайте про `.isRequired`, без этого не контролируется что пропс передаётся.

2023-04-21 16:08 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        ingredients.find((ing) => ing._id === item.id && ing.type === "bun")
**Можно лучше:**

Здесь и далее;

Авы уверены, что нужно проверять нахождение ингредиента в массиве) может быть стоит просто проверить тип?

2023-04-21 16:08 UTC, ArslanDev666 commented on src/components/BurgerIngredients/Ingredient/Ingredient.jsx
> +  let count = 0;
**Надо исправить:**

для расчёта `count`, используйте `useMemo`. Либо придумайте как получить `count` сразу, без изменения значения.

2023-04-21 16:08 UTC, ArslanDev666 commented on src/services/actions/ingredients.js
> +    requestToServ('ingredients').then(res => {
**Надо исправить:**

здесь и далее.

вы также должны обрабатывать блок `catch`, чтобы правильно обработать ошибки.

2023-04-22 14:54 UTC, VRbud commented
Добавил обработку ошибок в запросах на сервер, исправил count, разделил стор, поставил null значения для пустых значений в reducer
Наставник сказал что можно оставить для cart пустой массив.

2023-04-23 08:39 UTC, ArslanDev666 commented
> для cart пустой массив

Вроде бы, я не говорил ничего про массивы и `cart`

2023-04-23 08:56 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header иконка тоже должна быть обёрнута в ссылку;

- <https://disk.yandex.com/i/i8nDIGvfquQ2Kg> - Тут лучше написать не ингредиента, а булку.

- У вас возникает ошибка, если попытаться поменять ингредиенты местами: <https://disk.yandex.com/i/T9GuQsVSSXFCuw>;

### **Сделает код лучше:**

- <https://disk.yandex.com/i/pCKTGj5LjZpwFQ> - активной должна быть только первая ссылка, а не все;

2023-04-23 08:56 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            {cart !== null && cart.length > 0 ? (
**Надо исправить:**

`cart` никогда не будет равняться `null`, поэтому проверка избыточна.

2023-04-23 08:56 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                  key={uuidv4()}
**Можно лучше:**

не стоит в качетсве `key` использовать генерируимое значение, т.к. это будет вызываться ререндер всех элементов, при ререндере родителя.

https://react.dev/learn/rendering-lists#rules-of-keys

2023-04-23 08:56 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            {bun !== null && bun.name ? (
**Надо исправить:**

Проверка на `bun.name`, тут избыточна

2023-04-23 12:44 UTC, VRbud commented
Убрал лишние проверки, исправил id. Ставил рандомный id потом что в консоли выдавало ошибку что в списке(cart) есть элементы с одинаковым key. 
Сортировка у меня работает и в хроме и в сафари (https://disk.yandex.com/i/zLW807Aihzamtg). Не знаю в чем может быть проблема

2023-04-23 15:22 UTC, VRbud commented
Добавил удаление, обратно поставил рандомно генерируемый ключ, потому что при перетаскивании создавались дубликаты перетаскиваемых элементов. в глобальном сейте корзина пустая а на странице они отображались. так как key был одинаковый.

2023-04-24 05:41 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Советую не использовать новые свойства, т.к. проблема с моей стороны, по причине того что не у всех пользователей могут быть последнии версии браузеров, всегда проверяйте новые фичи тут: <https://caniuse.com/?search=toSpliced> (тут удобнее, т.к. видно сколько пользователей используют ту или иную версию браузера), или в MDN;

2023-04-24 07:42 UTC, merged