Sprint 3/step 1
VRbud/react-burger-yp pull request #5
Opened 2023-05-03 18:59 UTC by VRbud

Добавил роутинг. при входе на Страницу. Если нет пользователя автоматически логинит, если есть куки, и переносит пользователя в конструктор

2023-05-03 20:15 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая организация хранилища для работы авторизации
- используете тег `form`
- Правильная работа с куками

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Если токена нет в куках, то и не нужно делать на него запрос. Токен нужно запрашивать только тогда, когда нынешний протух и его нужно обновить, каждый раз запрашивать его при перезагрузке страницы тоже не нужно.

<img width="1439" alt="Снимок экрана 2023-05-03 в 22 58 10" src="https://user-images.githubusercontent.com/60173362/236033973-97d87d9d-86e3-442b-8eab-4985633659c6.png">

- Страница "Конструктора" должна быть доступна не авторизованному юзеру
- Страница "Регистрации" недоступна со страницы логина
- При отправке имейла  для восстановления пароля - возникает ошибка и юзер остается на текущей странице, хотя необходимо редиректить на страницу `reset-password`

<img width="865" alt="Снимок экрана 2023-05-03 в 23 00 50" src="https://user-images.githubusercontent.com/60173362/236034666-e3a5e4db-4526-498d-ab76-c41c620f881a.png">

- На странице профиля у формы изменения данных не появляется кнопки "Отмена" и "Сохранить".

- У вас запрос данных юзера срабатывает 4 раза. Из-за того, что приложение обернуто в `<React.StrictMode>` все запросы уходят дважды, но 4 это слишком много. Всё дело в том, что вы вызываете запрос `checkLogin` в двух местах.

- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-03 20:15 UTC, andryxxa93 commented on src/components/App/App.jsx
> +        <Route path="/login" element={<LoginPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-05-03 20:15 UTC, andryxxa93 commented on src/components/App/App.jsx
> +          <Route path="/img/:id" element={<Modal />} />
**Можно лучше**
В брифе нет роута с таким адресом

2023-05-03 20:15 UTC, andryxxa93 commented on src/components/ForgotForm/ForgotForm.jsx
> +        onSubmit={(e) => handleSubmit(e)}
**Можно лучше**
Тут можно проще - `onSubmit={handleSubmit}`

2023-05-03 20:15 UTC, andryxxa93 commented on src/pages/LoginPage.jsx
> +      navigate("/");
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-05-03 20:15 UTC, andryxxa93 commented on src/services/api/api.js
> +export function setCookie(name, value, props) {
**Можно лучше**
Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
setCookie('name', value, { path: '/' }).
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.

2023-05-04 04:51 UTC, VRbud commented
Переделал защиту на 'reset-password'(переадресация происходит только если пришел ответ что юзер существует, соответственно если нет сообщения то кидает на 'forgot-password') кнопки добавил, если нет токенов запросы не отправляются, конструктор доступен, регистрация доступна, исправил модальные окна

2023-05-04 20:16 UTC, andryxxa93 commented
**Необходимо исправить**
- Юзер должен иметь возможность изменить одно поле из личных данных, сейчас необходимо изменить имя и имейл, чтобы кнопка "Сохранить" стала активной.
- При запросах, использующих accessToken, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.
- При переходе на `reset-password` есть несколько быстрых перебросов туда обратно.

https://user-images.githubusercontent.com/60173362/236318640-834397e5-007a-416c-bebd-037787f02e0f.mov


**Можно лучше**
- После процедуры регистрации необходимо перенаправлять юзера на главную страницу. Так как запрос возвращает токены, то можно и сразу авторизровать

2023-05-04 22:26 UTC, VRbud commented
исправил недочету, добавил комментарии в функциях работы с токенами

2023-05-05 06:53 UTC, andryxxa93 commented
**Необходимо исправить**
- При запросах, использующих accessToken, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

Для проверки ответа можете создать функцию, которая принимает `url` и опции запроса (хедеры и.т.п). Эта функция должна сначала сделать запрос по адресу с опциями, если запрос падает с ошибкой  `jwt-expired`, то нужно обновить accessToken с помощью refreshToken. После обновления необходимо просто повторить ранее неудавшийся запрос, но используя уже свежий токен.

2023-05-05 23:09 UTC, VRbud commented
Я понял почему не работало!
Исправил

2023-05-06 16:47 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-06 16:48 UTC, VRbud commented
Спасибо!

2023-05-13 12:27 UTC, merged