Sprint 5/step 1
VRbud/react-burger-yp pull request #7
Opened 2023-06-07 14:36 UTC by VRbud

2023-06-07 15:05 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Сокеты открываются и закрываются согласно брифу
- Хорошая типизация хранилища и хуков useSelector и useDispatch

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В запрос на оформление заказа необходимо в хедерах передавать токен, чтобы бек понимал от кого пришел заказа, об этом написано в тех задании.
- При открытии заказа из Ленты по прямой ссылке - ошибка. Если открыть заказ из Истории, то вообще 404 страница.

<img width="1431" alt="Снимок экрана 2023-06-07 в 17 58 30" src="https://github.com/VRbud/react-burger-yp/assets/60173362/83cb0a14-270e-4d0d-b9a2-d69210d0c8a5">

<img width="984" alt="Снимок экрана 2023-06-07 в 17 59 17" src="https://github.com/VRbud/react-burger-yp/assets/60173362/48e9d9a3-109b-480d-9646-7e47ea755002">


- Если открыть Историю заказов, а потом Ленту, то в Ленте показываются заказы юзера из Истории. 

- В проекте должен быть универсальный socketMiddleware. Нужно передавать объект с типами в вызов для повышения универсальности и независимости от внешних данных. Передавать url можно через payload с уже полными данными для отправки (токеном и тд). Посоветуйтесь с наставником
- В проекте присутствуют много ts-ignore - от части из них следует избавиться.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-07 15:05 UTC, andryxxa93 commented on src/components/App/App.tsx
> +        <Route path="/feed/:id" element={<FeedOrder />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-06-07 15:05 UTC, andryxxa93 commented on src/services/middleware/wsMiddleware.ts
> +          const { data } = event;
**Можно лучше**

Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-06-08 04:28 UTC, VRbud commented
Добавил обновление кук, ошибки при прямом переходе на заказ с id, отправку заказа с токеном

2023-06-08 06:56 UTC, andryxxa93 commented
**Необходимо исправить**
- В карточке заказа не отображаются булки, хотя если открыть детали заказа - они есть
<img width="844" alt="Снимок экрана 2023-06-08 в 09 48 12" src="https://github.com/VRbud/react-burger-yp/assets/60173362/1d865803-5798-431c-a065-a2be21873a91">

- У вас при открытии деталей заказа срабатывает переподключение к веб-сокету и при закрытии тоже. Очень много получается подключений-отключений и получений сообщений от сокета - из-за этого приложение ведёт себя не стабильно. Рекомендую добавить `setTimeout`, чтобы новое подключение к сокету не происходило слишком часто.

- Если открыть заказ из Истории по прямой ссылке - просто перекидывает на страницу профидя.

2023-06-08 16:03 UTC, VRbud commented
Все исправил
Таймер установил 
страничка с личным заказом из истории правильно прогружается 
все булки на месте)
P.S.
честно не знал что куки привязаны к урл а не к вкладке браузера

2023-06-09 06:09 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-09 11:37 UTC, merged